### ISSUE TITLE
Wrong image for Vehicles->Kick Player From Vehicle

### ISSUE THREAD

**Issue by Ldalvik** [forgewiki/forgewiki#39]
Incorrect image for this scripting block: https://www.forgewiki.com/scripting/vehicles/kick-player-from-vehicle

**Comment by matthew-willis** [comment]
@Ldalvik Thanks for identifying this! 

When you're moving fast, mistakes were made :) 

Updated in the code and will be pushing an update soon.

**Comment by matthew-willis** [comment]
Updated.
